# Example SecureCodeBox Scan for Rust Projects
# This file shows how to create a scan that analyzes a Rust project for vulnerabilities

apiVersion: execution.securecodebox.io/v1
kind: Scan
metadata:
  # Give your scan a descriptive name
  name: rust-vulnerability-scan
  # Optional: add labels
  labels:
    app: my-rust-app
    team: security
spec:
  # This must match the name of your installed ScanType
  # If you installed with 'helm install rust-scanner ./helm', use 'rust-scanner'
  scanType: rust-scanner
  
  # Volumes define where your Rust code comes from
  volumes:
    # Mount code from a host path (common in CI/CD)
    - name: project-code
      hostPath:
        # IMPORTANT: Update this to point to your actual Rust project
        # The project MUST contain a Cargo.lock file for cargo-audit to work
        path: /path/to/your/rust/project
        type: Directory
  
  # Volume mounts specify where to mount the volumes in the scanner container
  volumeMounts:
    - name: project-code
      # The scanner expects the project to be mounted at /scan
      mountPath: /scan
